### ISSUE TITLE
使用模板里的样例无法为玩家添加多个capability

### ISSUE THREAD

**Issue by kawaiior** [Flandre923/MinecrafExampleMod#1]
为玩家添加多个capability时，通过playerEntity.getCapability(ModCapability.EXAMPLE_POWER);获取玩家cap时，只能获取到第一个注册的cap，然后会在ifPresent函数调用时抛出ClassCastException

`
if(capability.isPresent()&& originalCapability.isPresent()){
            capability.ifPresent((cap)->{
                originalCapability.ifPresent(originalCap->{
                    cap.setExamplePower(originalCap.getExamplePower());
                    NetworkRegistryHandler.CHANNEL.send(PacketDistributor.PLAYER.with(()->(ServerPlayerEntity) player),new Power(cap.getExamplePower()));
                });
            });
        }
`

> java.lang.ClassCastException: github.kawaiior.yuanchuxiuzhen.common.capability.ManaPower cannot be cast to github.kawaiior.yuanchuxiuzhen.common.capability.ExamplePower
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[forge-1.16.5-36.2.34_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
	at github.kawaiior.yuanchuxiuzhen.core.init.event.ExmplePowerEvent.onPlayerJoin(ExmplePowerEvent.java:40) ~[main/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_20_ExmplePowerEvent_onPlayerJoin_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.addPlayer(ServerWorld.java:806) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.addNewPlayer(ServerWorld.java:798) ~[forge:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:186) ~[forge:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.tryAcceptPlayer(ServerLoginNetHandler.java:122) ~[forge:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.tick(ServerLoginNetHandler.java:66) ~[forge:?] {re:classloading}
	at net.minecraft.network.NetworkManager.tick(NetworkManager.java:244) ~[forge:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.tick(NetworkSystem.java:151) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:899) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:821) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:84) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_371] {}

我的代码已上传至gitee，暂时没有搞清楚为什么会出现这个异常
[https://gitee.com/kawaiior/ycxz-1.16.5](url)

**Comment by kawaiior** [comment]
问题解决了，解决方法是在CapabilityRegistryHandler这个类上加上@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)这个注解，模板中的是@Mod.EventBusSubscriber，是没有传参的。如果不传参的话，会导致事件无法正常触发，从而导致Cap没有被注册，进而导致获取时只能获取到第一个Cap。同时，我发现如果是在Mod主类中使用MinecraftForge.EVENT_BUS.register同样是无法触发这个事件的。具体原因尚不清楚。
